# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('upd_date', models.DateField()),
                ('category', models.CharField(choices=[('DAX', 'DynAX'), ('Net', 'DotNet'), ('sql', 'Sql')], default='DAX', max_length=3)),
                ('completed', models.BooleanField()),
                ('days_allocated', models.IntegerField(default=1)),
                ('user_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
