# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170529_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upd_date',
            field=models.DateField(auto_now=True),
        ),
    ]
